// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA24QOygi4VMdpYUm450qMhxnSe_nR5jbA',
    appId: '1:306531011914:web:f49c40c5e4cbb7768c05b3',
    messagingSenderId: '306531011914',
    projectId: 'mezz-3c847',
    authDomain: 'mezz-3c847.firebaseapp.com',
    storageBucket: 'mezz-3c847.firebasestorage.app',
    measurementId: 'G-SKX127W12M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKEx9_YgQr2MdkBngChNgt3SDW0lGzJlk',
    appId: '1:306531011914:android:fb35d4cbf73e28968c05b3',
    messagingSenderId: '306531011914',
    projectId: 'mezz-3c847',
    storageBucket: 'mezz-3c847.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtcTTsxE60f_pwlzxSEBq6cAG4nsc0Ti0',
    appId: '1:306531011914:ios:c36c797838c95b8b8c05b3',
    messagingSenderId: '306531011914',
    projectId: 'mezz-3c847',
    storageBucket: 'mezz-3c847.firebasestorage.app',
    iosBundleId: 'com.mezz.mezz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtcTTsxE60f_pwlzxSEBq6cAG4nsc0Ti0',
    appId: '1:306531011914:ios:c36c797838c95b8b8c05b3',
    messagingSenderId: '306531011914',
    projectId: 'mezz-3c847',
    storageBucket: 'mezz-3c847.firebasestorage.app',
    iosBundleId: 'com.mezz.mezz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA24QOygi4VMdpYUm450qMhxnSe_nR5jbA',
    appId: '1:306531011914:web:bcdae96242f068298c05b3',
    messagingSenderId: '306531011914',
    projectId: 'mezz-3c847',
    authDomain: 'mezz-3c847.firebaseapp.com',
    storageBucket: 'mezz-3c847.firebasestorage.app',
    measurementId: 'G-LW9YW61PXZ',
  );
}
